
insert into seriado(nome) values ('American Horror Story');
insert into seriado(nome) values ('Ancient Aliens'); 
insert into seriado(nome) values ('Anger Management');
insert into seriado(nome) values ('Arrow'); 
insert into seriado(nome) values ('Bates Motel'); 
insert into seriado(nome) values ('Believe'); 
insert into seriado(nome) values ('Boardwalk Empire');
insert into seriado(nome) values ('Californication'); 
insert into seriado(nome) values ('Castle'); 
insert into seriado(nome) values ('Continuum');
insert into seriado(nome) values ('Criminal Minds'); 
insert into seriado(nome) values ('Da Vinci''s Demons');
insert into seriado(nome) values ('Defiance'); 
insert into seriado(nome) values ('Elementary');
insert into seriado(nome) values ('Falling Skies');
insert into seriado(nome) values ('Gadget Man'); 
insert into seriado(nome) values ('Game of Thrones');
insert into seriado(nome) values ('Glee'); 
insert into seriado(nome) values ('Hannibal');
insert into seriado(nome) values ('Helix'); 
insert into seriado(nome) values ('Homeland');
insert into seriado(nome) values ('How I Met Your Mother');
insert into seriado(nome) values ('In the Flesh'); 
insert into seriado(nome) values ('Mad Men'); 
insert into seriado(nome) values ('Marvel''s Agents of S.H.I.E.L.D.'); 
insert into seriado(nome) values ('Paranormal Witness'); 
insert into seriado(nome) values ('Person of Interest'); 
insert into seriado(nome) values ('Revenge'); 
insert into seriado(nome) values ('Revolution');
insert into seriado(nome) values ('Sherlock'); 
insert into seriado(nome) values ('Sleepy Hollow'); 
insert into seriado(nome) values ('Supernatural'); 
insert into seriado(nome) values ('The After'); 
insert into seriado(nome) values ('The Apprentice UK');
insert into seriado(nome) values ('The Apprentice US');
insert into seriado(nome) values ('The Big Bang Theory');
insert into seriado(nome) values ('The Following');
insert into seriado(nome) values ('The Killing (US)');
insert into seriado(nome) values ('The Mentalist'); 
insert into seriado(nome) values ('The Middle');
insert into seriado(nome) values ('The Walking Dead'); 
insert into seriado(nome) values ('True Blood'); 
insert into seriado(nome) values ('Two and a Half Men');
insert into seriado(nome) values ('Under the Dome'); 
insert into seriado(nome) values ('Vikings'); 